# Generated by Django 6.0 on 2026-02-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_customer_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
