# Generated by Django 6.0 on 2026-02-27 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_status_alter_bookingtimeline_booking_and_more'),
        ('payments', '0003_alter_payment_gateway_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='gateway_response',
        ),
        migrations.AlterField(
            model_name='commission',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(max_length=50),
        ),
    ]
