# Generated by Django 6.0 on 2026-03-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='gateway_response',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('Card', 'Card'), ('Cash', 'Cash')], max_length=20, null=True),
        ),
    ]
