# Generated by Django 6.0 on 2026-03-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_payment_gateway_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('Card', 'Card'), ('Cash', 'Cash')], default='UPI', max_length=20),
        ),
    ]
