# Generated by Django 6.0.2 on 2026-03-13 12:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplaintType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of complaint type (e.g., 'Late Service', 'Rude Behavior')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of what this complaint type covers",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Uncheck to hide this type from users"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Complaint Type",
                "verbose_name_plural": "Complaint Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complaint_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Unique complaint reference (e.g., CMP-2024-00001)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "complainant_role",
                    models.CharField(
                        choices=[("customer", "Customer"), ("partner", "Partner")],
                        default="customer",
                        help_text="Role of the person filing complaint",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        help_text="Priority level",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected"),
                            ("escalated", "Escalated"),
                            ("closed", "Closed"),
                        ],
                        default="pending",
                        help_text="Current status",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Short summary of complaint",
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(5)],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description",
                        max_length=5000,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(
                        blank=True, default=list, help_text="List of attachment URLs"
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about resolution",
                        max_length=5000,
                        null=True,
                    ),
                ),
                (
                    "resolution_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("refund", "Refund"),
                            ("partial_refund", "Partial Refund"),
                            ("re_service", "Re-service"),
                            ("wallet_credit", "Wallet Credit"),
                            ("partner_warning", "Partner Warning"),
                            ("partner_suspension", "Partner Suspension"),
                            ("partner_block", "Partner Block"),
                            ("no_action", "No Action"),
                        ],
                        help_text="Type of resolution",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "resolution_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Refund/credit amount if applicable",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When complaint was resolved", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "against_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User being complained against (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaints_against",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin handling this complaint",
                        limit_choices_to={"role": "admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related booking (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaints",
                        to="bookings.booking",
                    ),
                ),
                (
                    "complainant",
                    models.ForeignKey(
                        help_text="User who filed the complaint",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints_filed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "complaint_type",
                    models.ForeignKey(
                        help_text="Type of complaint",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="complaints",
                        to="complaints.complainttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplaintEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload evidence file",
                        upload_to="complaints/evidence/%Y/%m/%d/",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("document", "Document"),
                            ("video", "Video"),
                            ("other", "Other"),
                        ],
                        default="image",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Brief description of this evidence",
                        max_length=255,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_files",
                        to="complaints.complaint",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Complaint evidence",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplaintHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(help_text="What action was taken", max_length=100),
                ),
                (
                    "old_value",
                    models.JSONField(
                        blank=True, help_text="Previous values", null=True
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(blank=True, help_text="New values", null=True),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action_by",
                    models.ForeignKey(
                        help_text="User who performed this action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="complaints.complaint",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Complaint histories",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["complaint_id"], name="complaints__complai_ea9dba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(fields=["status"], name="complaints__status_7c8de0_idx"),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["priority"], name="complaints__priorit_f4170d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["complainant"], name="complaints__complai_ff8001_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["created_at"], name="complaints__created_805464_idx"
            ),
        ),
    ]
